// <auto-generated />
/*
  Descripción rápida:
  - Archivo generado por EF Core que representa el "modelo objetivo" tras aplicar la migración
    20251112163114_Estudiante_CRUD_Initial.
  - NO editar lógicamente: se regenera con migraciones. Sólo sirve para referencia/documentación.
  Conexiones:
  - ApplicationDbContext (origen del modelo)
  - Models\{Empresa,Estudiante,Pasantia,Aplicacion,Usuario}.cs
  - Migrations\20251112163114_Estudiante_CRUD_Initial.cs (operaciones Up/Down)
*/
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UAMPass.Models;

#nullable disable

namespace UAMPass.Migrations
{
    [DbContext(typeof(ApplicationDbContext))] // Indica el DbContext al que pertenece esta migración
    [Migration("20251112163114_Estudiante_CRUD_Initial")] // Identificador de la migración
    partial class Estudiante_CRUD_Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Metadatos del snapshot: versión EF Core y límite de longitud de identificadores del proveedor
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            // Configura el uso de columnas IDENTITY por defecto en PostgreSQL (autoincrement)
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Entidad: Aplicacion (tabla "Aplicaciones")
            modelBuilder.Entity("UAMPass.Models.Aplicacion", b =>
            {
                // Id: PK entero, valor generado al insertar (IDENTITY)
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                // Aplica la estrategia IDENTITY específica de Npgsql para la columna Id
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                // Comentarios: texto opcional
                b.Property<string>("Comentarios")
                    .HasColumnType("text");

                // EstudianteId: FK hacia Estudiantes (entero)
                b.Property<int>("EstudianteId")
                    .HasColumnType("integer");

                // FechaAplicacion: timestamptz (fecha con zona horaria)
                b.Property<DateTime>("FechaAplicacion")
                    .HasColumnType("timestamp with time zone");

                // PasantiaId: FK hacia Pasantias (entero)
                b.Property<int>("PasantiaId")
                    .HasColumnType("integer");

                // Status: entero (usualmente mapea un enum en el modelo)
                b.Property<int>("Status")
                    .HasColumnType("integer");

                b.HasKey("Id"); // Clave primaria sobre Id

                // Índices para optimizar joins/consultas por FK
                b.HasIndex("EstudianteId");
                b.HasIndex("PasantiaId");

                b.ToTable("Aplicaciones"); // Nombre físico de la tabla
            });

            // Entidad: Empresa (tabla "Empresas")
            modelBuilder.Entity("UAMPass.Models.Empresa", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                // ContactoEmail: requerido (NOT NULL)
                b.Property<string>("ContactoEmail")
                    .IsRequired()
                    .HasColumnType("text");

                // Direccion: requerido, longitud máxima 200
                b.Property<string>("Direccion")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                // Nombre: requerido, longitud máxima 150
                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("character varying(150)");

                // SitioWeb: campo opcional
                b.Property<string>("SitioWeb")
                    .HasColumnType("text");

                b.HasKey("Id"); // PK
                b.ToTable("Empresas");
            });

            // Entidad: Estudiante (tabla "Estudiantes")
            modelBuilder.Entity("UAMPass.Models.Estudiante", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                // CareersCsv: texto con carreras separadas por comas (opcional)
                b.Property<string>("CareersCsv")
                    .HasColumnType("text");

                // Correo: requerido, max 150
                b.Property<string>("Correo")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("character varying(150)");

                // Facultad: requerido, max 100
                b.Property<string>("Facultad")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                // FechaRegistro: fecha con zona horaria
                b.Property<DateTime>("FechaRegistro")
                    .HasColumnType("timestamp with time zone");

                // Nombre: requerido, max 120
                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasMaxLength(120)
                    .HasColumnType("character varying(120)");

                b.HasKey("Id");
                b.ToTable("Estudiantes");
            });

            // Entidad: Pasantia (tabla "Pasantias")
            modelBuilder.Entity("UAMPass.Models.Pasantia", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                // Aprobada: booleano que indica visibilidad/aprobación de la pasantía
                b.Property<bool>("Aprobada")
                    .HasColumnType("boolean");

                // Descripcion: requerido (texto)
                b.Property<string>("Descripcion")
                    .IsRequired()
                    .HasColumnType("text");

                // EmpresaId: FK hacia Empresas
                b.Property<int>("EmpresaId")
                    .HasColumnType("integer");

                // FechaPublicacion: fecha de publicación (timestamptz)
                b.Property<DateTime>("FechaPublicacion")
                    .HasColumnType("timestamp with time zone");

                // RequiredCareersCsv: carreras requeridas en CSV (opcional)
                b.Property<string>("RequiredCareersCsv")
                    .HasColumnType("text");

                // Titulo: requerido, max 200
                b.Property<string>("Titulo")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.HasKey("Id");

                // Índice para FK EmpresaId
                b.HasIndex("EmpresaId");

                b.ToTable("Pasantias");
            });

            // Entidad: Usuario (tabla "Usuarios")
            modelBuilder.Entity("UAMPass.Models.Usuario", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                // Contrasena: requerido. Asegurarse de almacenar hashes en el modelo real.
                b.Property<string>("Contrasena")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                // Correo: requerido
                b.Property<string>("Correo")
                    .IsRequired()
                    .HasColumnType("text");

                // Nombre: requerido, max 100
                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                // Rol: requerido, max 50 (ej. Admin, Empresa, Estudiante)
                b.Property<string>("Rol")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.HasKey("Id");
                b.ToTable("Usuarios");
            });

            // Relaciones: Aplicacion -> Estudiante y Pasantia (FKs con cascada)
            modelBuilder.Entity("UAMPass.Models.Aplicacion", b =>
            {
                b.HasOne("UAMPass.Models.Estudiante", "Estudiante") // navegación desde Aplicacion hacia Estudiante
                    .WithMany("Aplicaciones") // Estudiante tiene colección Aplicaciones
                    .HasForeignKey("EstudianteId") // FK definida en Aplicaciones
                    .OnDelete(DeleteBehavior.Cascade) // cascada al borrar estudiante
                    .IsRequired(); // FK no admite null

                b.HasOne("UAMPass.Models.Pasantia", "Pasantia") // navegación desde Aplicacion hacia Pasantia
                    .WithMany("Aplicaciones")
                    .HasForeignKey("PasantiaId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                // Propiedades de navegación explícitas para EF
                b.Navigation("Estudiante");
                b.Navigation("Pasantia");
            });

            // Relación: Pasantia -> Empresa (cada pasantía pertenece a una empresa)
            modelBuilder.Entity("UAMPass.Models.Pasantia", b =>
            {
                b.HasOne("UAMPass.Models.Empresa", "Empresa")
                    .WithMany("Pasantias") // Empresa tiene colección Pasantias
                    .HasForeignKey("EmpresaId")
                    .OnDelete(DeleteBehavior.Cascade) // borrar empresa borra sus pasantías
                    .IsRequired();

                b.Navigation("Empresa");
            });

            // Declaración de propiedades de navegación en otras entidades (para referencia interna de EF)
            modelBuilder.Entity("UAMPass.Models.Empresa", b =>
            {
                b.Navigation("Pasantias");
            });

            modelBuilder.Entity("UAMPass.Models.Estudiante", b =>
            {
                b.Navigation("Aplicaciones");
            });

            modelBuilder.Entity("UAMPass.Models.Pasantia", b =>
            {
                b.Navigation("Aplicaciones");
            });
#pragma warning restore 612, 618
        }
    }
}