// <auto-generated />
/*
  Migración "Inicial" (archivo Designer) — descripción breve:
  - Representa el modelo objetivo que EF Core espera tras aplicar la migración "20251110045506_Inicial".
  - No editar manualmente salvo para documentación; se regenera al crear migraciones.
  - Conecta con: ApplicationDbContext, Models\Usuario.cs y el archivo de migración 20251110045506_Inicial.cs.
*/

using Microsoft.EntityFrameworkCore; // ModelBuilder, EntityTypeBuilder, etc.
using Microsoft.EntityFrameworkCore.Infrastructure; // Metadata helpers
using Microsoft.EntityFrameworkCore.Migrations; // tipos de migración
using Microsoft.EntityFrameworkCore.Storage.ValueConversion; // (importado por generación)
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata; // extensiones específicas de Npgsql (Postgres)
using UAMPass.Models; // espacio de nombres con las entidades del dominio

#nullable disable // Snapshot/migración generada sin anotaciones nullable

namespace UAMPass.Migrations
{
    // Indica el DbContext objetivo para esta migración
    [DbContext(typeof(ApplicationDbContext))]

    // Identificador de la migración (timestamp + nombre)
    [Migration("20251110045506_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        // Construye el modelo objetivo que EF usará para comparar/crear la migración
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618 // suprime warnings de código autogenerado

            // Metadatos del modelo: versión de EF Core y límite de longitud de identificadores del proveedor
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            // Configura el uso de columnas IDENTITY por defecto para PostgreSQL (autoincrement)
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Definición de la entidad Usuario (tabla "Usuarios")
            modelBuilder.Entity("UAMPass.Models.Usuario", b =>
            {
                // Columna Id: entero, clave primaria, valor generado al insertar (IDENTITY)
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                // Fuerza la estrategia IDENTITY específica de Npgsql para la columna Id
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                // Contrasena: requerido (NOT NULL), max length 100, tipo en DB character varying(100)
                // Atención: el modelo debe almacenar contraseñas de forma segura (hash + salt) — aquí solo se define la columna.
                b.Property<string>("Contrasena")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                // Correo: requerido (NOT NULL), mapeado a tipo text en PostgreSQL
                b.Property<string>("Correo")
                    .IsRequired()
                    .HasColumnType("text");

                // Nombre: requerido, longitud máxima 100
                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                // Rol: requerido, longitud máxima 50 (por ejemplo "Admin", "Empresa", "Estudiante")
                b.Property<string>("Rol")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                // Define la clave primaria sobre Id
                b.HasKey("Id");

                // Indica el nombre de la tabla en la base de datos
                b.ToTable("Usuarios");
            });
#pragma warning restore 612, 618 // restaurar warnings
        }
    }
}