// <auto-generated />
/*
    DESCRIPCIÓN GENERAL 
    ---------------------------------------------------
    Este archivo es un "Model Snapshot" generado por Entity Framework Core para el DbContext
    ApplicationDbContext. Contiene una representación serializada del modelo EF (entidades,
    propiedades, índices y relaciones) tal como EF lo conoce en el momento de la última migración.

    Propósito:
    - Permite a las herramientas de migración de EF comparar el modelo actual del código con
      el modelo en el snapshot para generar nuevas migraciones.
    - No es la definición original del modelo: el origen del modelo es ApplicationDbContext
      (método OnModelCreating) y las clases en Models/*.cs.
    - En general no se edita manualmente; se regenera cuando se crea una migración.

    Conexiones con otros archivos del proyecto:
    - ApplicationDbContext.cs : DbContext que define OnModelCreating y registra las entidades.
    - Models\*.cs : clases de entidad que representan Aplicacion, Empresa, Estudiante, Pasantia, Usuario.
    - Migrations\{timestamp}_*.cs : archivos de migración que usan este snapshot para crear scripts.
    - Program.cs / Startup.cs : lugar donde se registra ApplicationDbContext con services.AddDbContext.
    - UAMPass.csproj : referencia al proveedor de EF Core (Npgsql.EntityFrameworkCore.PostgreSQL).
    - Base de datos PostgreSQL: las columnas usan tipos PostgreSQL (ej. "integer", "text", "timestamp with time zone").

    Cómo usar este comentario:
    - Usar para entender las tablas y relaciones actuales que EF espera.
    - Buscar en Models\ para ver las anotaciones/propiedades originales de cada clase.
    - Revisar Migrations\ para ver cómo se aplicaron cambios anteriores al esquema.

    NOTA SOBRE LA GENERACIÓN:
    - Las llamadas a métodos NpgsqlModelBuilderExtensions y NpgsqlPropertyBuilderExtensions provienen
      del proveedor Npgsql de EF Core y configuran el comportamiento de identidad/autoincrement
      y los tipos específicos de PostgreSQL.

    EXPLICACIÓN LÍNEA A LÍNEA / SECCIONES IMPORTANTES
    ------------------------------------------------
    using ...         -> Importa los espacios de nombres necesarios. Incluye tipos EF Core y Npgsql.
    #nullable disable -> Indica que el snapshot fue generado sin anotaciones de referencia nullable.

    [DbContext(typeof(ApplicationDbContext))]
        - Vincula este snapshot al tipo ApplicationDbContext. EF usa esto para saber a qué DbContext
          pertenece el snapshot.

    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
        - La clase que contiene la representación del modelo. Hereda ModelSnapshot usado por EF.

    protected override void BuildModel(ModelBuilder modelBuilder)
        - Método principal: construye el modelo en el ModelBuilder exactamente como EF lo ve.
        - Dentro de este método está la configuración de entidades, propiedades y relaciones.

    modelBuilder.HasAnnotation("ProductVersion", "9.0.10")
        - Anotación que indica la versión de EF Core que generó el snapshot.
      .HasAnnotation("Relational:MaxIdentifierLength", 63)
        - Longitud máxima de identificadores relacionales (nombres de tablas/columnas) para el proveedor.

    NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
        - Configura el uso de "IDENTITY" por defecto para columnas autoincrement en PostgreSQL.

    modelBuilder.Entity("UAMPass.Models.Aplicacion", b => { ... });
        - Inicio de la configuración para la entidad Aplicacion.
        - b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
            - Define la columna Id de tipo integer y que su valor se genera al insertar (autoincrement).
        - NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
            - Asegura que el proveedor Npgsql use la estrategia IDENTITY para esa columna.
        - b.Property<string>("Comentarios").HasColumnType("text");
            - Columna Comentarios almacenada como text (nullable por ausencia de IsRequired()).
        - b.Property<int>("EstudianteId").HasColumnType("integer");
            - Foreign key hacia Estudiante (columna no nula porque la relación luego indica IsRequired).
        - b.Property<DateTime>("FechaAplicacion").HasColumnType("timestamp with time zone");
            - DateTime mapeado a timestamp with time zone (UTC-aware en PostgreSQL).
        - b.Property<int>("Status").HasColumnType("integer");
            - Enum o entero que representa estado; revisar Models\Aplicacion.cs para semántica.
        - b.HasKey("Id");
            - Define la clave primaria sobre Id.
        - b.HasIndex("EstudianteId"); y b.HasIndex("PasantiaId");
            - Índices creados para las columnas FK para acelerar consultas.
        - b.ToTable("Aplicaciones");
            - Nombre de tabla en la base de datos.

    modelBuilder.Entity("UAMPass.Models.Empresa", b => { ... });
        - Propiedades principales:
            - ContactoEmail: requerido (IsRequired), tipo text.
            - Direccion: requerido, max length 200, character varying(200).
            - Nombre: requerido, max length 150.
            - SitioWeb: texto opcional.
        - b.ToTable("Empresas");

    modelBuilder.Entity("UAMPass.Models.Estudiante", b => { ... });
        - Properties:
            - CareersCsv: CSV de carreras (text).
            - Correo: requerido, max 150.
            - Facultad: requerido, max 100.
            - FechaRegistro: timestamp with time zone.
            - Nombre: requerido, max 120.
        - b.ToTable("Estudiantes");

    modelBuilder.Entity("UAMPass.Models.Pasantia", b => { ... });
        - Properties:
            - Aprobada: boolean.
            - Descripcion: requerido (text).
            - EmpresaId: FK hacia Empresa.
            - FechaPublicacion: timestamp with time zone.
            - RequiredCareersCsv: text (carreras requeridas).
            - Titulo: requerido, max 200.
        - b.HasIndex("EmpresaId");
        - b.ToTable("Pasantias");

    modelBuilder.Entity("UAMPass.Models.Usuario", b => { ... });
        - Properties:
            - Contrasena: requerido, max 100. (Atención: revisar almacenamiento seguro en Models/logic)
            - Correo: requerido, text.
            - Nombre: requerido, max 100.
            - Rol: requerido, max 50.
        - b.ToTable("Usuarios");

    RELACIONES (sección con HasOne / WithMany)
    ------------------------------------------
    modelBuilder.Entity("UAMPass.Models.Aplicacion", b => {
        b.HasOne("UAMPass.Models.Estudiante", "Estudiante")
            .WithMany("Aplicaciones")
            .HasForeignKey("EstudianteId")
            .OnDelete(DeleteBehavior.Cascade)
            .IsRequired();
        - Relación: Aplicacion -> Estudiante (muchas Aplicaciones por Estudiante).
        - HasForeignKey("EstudianteId"): clave foránea almacenada en Aplicaciones.
        - OnDelete(DeleteBehavior.Cascade): si se borra el Estudiante, se borran sus Aplicaciones.
        - IsRequired(): la FK no permite null (es obligatoria).

        b.HasOne("UAMPass.Models.Pasantia", "Pasantia")
            .WithMany("Aplicaciones")
            .HasForeignKey("PasantiaId")
            .OnDelete(DeleteBehavior.Cascade)
            .IsRequired();
        - Relación similar para Pasantia.

        b.Navigation("Estudiante"); b.Navigation("Pasantia");
        - Indica propiedades de navegación existentes en la clase Aplicacion.
    });

    modelBuilder.Entity("UAMPass.Models.Pasantia", b => {
        b.HasOne("UAMPass.Models.Empresa", "Empresa")
            .WithMany("Pasantias")
            .HasForeignKey("EmpresaId")
            .OnDelete(DeleteBehavior.Cascade)
            .IsRequired();
        b.Navigation("Empresa");
    });
    - Una Pasantia pertenece a una Empresa; cascada de borrado también aplicada.

    modelBuilder.Entity("UAMPass.Models.Empresa", b => { b.Navigation("Pasantias"); });
    modelBuilder.Entity("UAMPass.Models.Estudiante", b => { b.Navigation("Aplicaciones"); });
    modelBuilder.Entity("UAMPass.Models.Pasantia", b => { b.Navigation("Aplicaciones"); });
    - Estas líneas enumeran propiedades de navegación para que EF tenga conocimiento de ellas.

    COMENTARIOS SOBRE TIPOS Y CONFIGURACIONES ESPECÍFICAS
    ---------------------------------------------------
    - HasColumnType("timestamp with time zone")
        -> Usado para DateTime; en .NET conviene que las fechas se manejen en UTC o con DateTimeKind adecuado.
    - .IsRequired() vs nullable:
        -> IsRequired indica NOT NULL en la columna.
    - MaxLength / HasMaxLength:
        -> Limita la longitud de la columna character varying(...) en la BD.
    - UseIdentityByDefaultColumns / UseIdentityByDefaultColumn:
        -> Configura que la BD genere valores de PK automáticamente usando la sintaxis IDENTITY de PostgreSQL.

    RECOMENDACIONES
    ---------------
    - Para entender el significado semántico (por ejemplo qué es "Status" o "CareersCsv"), revisar Models\*.cs
      (Aplicacion.cs, Pasantia.cs, Estudiante.cs, Empresa.cs, Usuario.cs).
    - Para cambios en el esquema, modificar las clases y/o ApplicationDbContext, luego ejecutar:
        __dotnet ef migrations add NombreDeLaMigracion__
      y EF actualizará este snapshot y generará los archivos de migración.
    - Evitar editar a mano este archivo salvo para documentación interna. Las herramientas de EF lo regeneran.

    MAPA RÁPIDO DE ARCHIVOS RELACIONADOS
    - ApplicationDbContext.cs                -> Origen del modelo (OnModelCreating)
    - Models\Aplicacion.cs                   -> Definición de la entidad Aplicacion
    - Models\Empresa.cs                      -> Definición de Empresa
    - Models\Estudiante.cs                   -> Definición de Estudiante
    - Models\Pasantia.cs                     -> Definición de Pasantia
    - Models\Usuario.cs                      -> Definición de Usuario
    - Migrations\{timestamp}_*.cs            -> Migraciones que generan cambios en la BD
    - UAMPass.csproj                          -> Paquetes, incluyendo Npgsql provider
    - Program.cs / Startup.cs                -> Registro del DbContext en el contenedor DI
*/

using System; // tipos básicos (DateTime, etc.)
using Microsoft.EntityFrameworkCore; // EF Core: ModelBuilder, DbContext, entidades
using Microsoft.EntityFrameworkCore.Infrastructure; // ModelSnapshot base clase
using Microsoft.EntityFrameworkCore.Storage.ValueConversion; // conversiones de valores (a veces usadas)
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata; // extensiones específicas de Npgsql (Postgres)
using UAMPass.Models; // espacio de nombres con las clases de entidad (Aplicacion, Empresa, ...)

#nullable disable // el snapshot se generó sin anotaciones nullable (evita advertencias de nullable)

namespace UAMPass.Migrations
{
    [DbContext(typeof(ApplicationDbContext))] // Indica a qué DbContext pertenece este snapshot
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder) // Reconstruye el modelo en tiempo de migración
        {
#pragma warning disable 612, 618 // suprime warnings generados por código autogenerado

            // Metadatos del snapshot (versión EF y límites del proveedor)
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10") // versión de EF Core que generó el snapshot
                .HasAnnotation("Relational:MaxIdentifierLength", 63); // límite de longitud para nombres en PG

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder); // usar IDENTITY por defecto en Postgres

            // ---------- Entidad: Aplicacion (tabla "Aplicaciones") ----------
            modelBuilder.Entity("UAMPass.Models.Aplicacion", b =>
            {
                // PK: Id, generado en la BD al insertar (autoincrement / IDENTITY)
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                // Fuerza la estrategia IDENTITY específica de Npgsql para la columna Id
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                // Comentarios: texto opcional (nullable)
                b.Property<string>("Comentarios")
                    .HasColumnType("text");

                // EstudianteId: FK hacia Estudiante (entero)
                b.Property<int>("EstudianteId")
                    .HasColumnType("integer");

                // FechaAplicacion: se mapea a timestamptz (timestamp with time zone)
                b.Property<DateTime>("FechaAplicacion")
                    .HasColumnType("timestamp with time zone");

                // PasantiaId: FK hacia Pasantia (entero)
                b.Property<int>("PasantiaId")
                    .HasColumnType("integer");

                // Status: entero (probablemente un enum en el modelo)
                b.Property<int>("Status")
                    .HasColumnType("integer");

                b.HasKey("Id"); // define la clave primaria sobre Id

                b.HasIndex("EstudianteId"); // índice para acelerar consultas por FK EstudianteId
                b.HasIndex("PasantiaId");   // índice para acelerar consultas por FK PasantiaId

                b.ToTable("Aplicaciones"); // nombre de la tabla en la base de datos
            });

            // ---------- Entidad: Empresa (tabla "Empresas") ----------
            modelBuilder.Entity("UAMPass.Models.Empresa", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                // ContactoEmail: requerido (NOT NULL)
                b.Property<string>("ContactoEmail")
                    .IsRequired()
                    .HasColumnType("text");

                // Direccion: requerido, longitud máxima 200
                b.Property<string>("Direccion")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                // Nombre: requerido, longitud máxima 150
                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("character varying(150)");

                // SitioWeb: texto opcional
                b.Property<string>("SitioWeb")
                    .HasColumnType("text");

                b.HasKey("Id"); // PK
                b.ToTable("Empresas"); // tabla
            });

            // ---------- Entidad: Estudiante (tabla "Estudiantes") ----------
            modelBuilder.Entity("UAMPass.Models.Estudiante", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                // CareersCsv: probable campo de texto con lista separada por comas
                b.Property<string>("CareersCsv")
                    .HasColumnType("text");

                // Correo: requerido, max length 150
                b.Property<string>("Correo")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("character varying(150)");

                // Facultad: requerido, max length 100
                b.Property<string>("Facultad")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                // FechaRegistro: timestamp con zona horaria
                b.Property<DateTime>("FechaRegistro")
                    .HasColumnType("timestamp with time zone");

                // Nombre: requerido, max length 120
                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasMaxLength(120)
                    .HasColumnType("character varying(120)");

                b.HasKey("Id");
                b.ToTable("Estudiantes");
            });

            // ---------- Entidad: Pasantia (tabla "Pasantias") ----------
            modelBuilder.Entity("UAMPass.Models.Pasantia", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                // Aprobada: booleano que indica si la pasantía fue aprobada
                b.Property<bool>("Aprobada")
                    .HasColumnType("boolean");

                // Descripcion: requerido, texto libre
                b.Property<string>("Descripcion")
                    .IsRequired()
                    .HasColumnType("text");

                // EmpresaId: FK hacia Empresa
                b.Property<int>("EmpresaId")
                    .HasColumnType("integer");

                // FechaPublicacion: fecha con zona horaria
                b.Property<DateTime>("FechaPublicacion")
                    .HasColumnType("timestamp with time zone");

                // RequiredCareersCsv: CSV con carreras requeridas (texto)
                b.Property<string>("RequiredCareersCsv")
                    .HasColumnType("text");

                // Titulo: requerido, max length 200
                b.Property<string>("Titulo")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.HasKey("Id");
                b.HasIndex("EmpresaId"); // índice para consultas por EmpresaId
                b.ToTable("Pasantias");
            });

            // ---------- Entidad: Usuario (tabla "Usuarios") ----------
            modelBuilder.Entity("UAMPass.Models.Usuario", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                // Contrasena: requerido, revisar almacenamiento seguro en el modelo (hashing)
                b.Property<string>("Contrasena")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                // Correo: requerido
                b.Property<string>("Correo")
                    .IsRequired()
                    .HasColumnType("text");

                // Nombre: requerido, max 100
                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                // Rol: requerido, max 50 (por ejemplo "Admin", "Empresa", "Estudiante")
                b.Property<string>("Rol")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.HasKey("Id");
                b.ToTable("Usuarios");
            });

            // ---------- Relaciones: Aplicacion -> Estudiante, Pasantia ----------
            modelBuilder.Entity("UAMPass.Models.Aplicacion", b =>
            {
                b.HasOne("UAMPass.Models.Estudiante", "Estudiante") // Aplicacion.Estudiantes navigation
                    .WithMany("Aplicaciones") // Estudiante tiene colección Aplicaciones
                    .HasForeignKey("EstudianteId") // FK en tabla Aplicaciones
                    .OnDelete(DeleteBehavior.Cascade) // borrar estudiante borra sus aplicaciones
                    .IsRequired(); // FK no admite null

                b.HasOne("UAMPass.Models.Pasantia", "Pasantia") // Aplicacion.Pasantia navigation
                    .WithMany("Aplicaciones")
                    .HasForeignKey("PasantiaId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Estudiante"); // información de navegación para EF
                b.Navigation("Pasantia");
            });

            // ---------- Relación: Pasantia -> Empresa ----------
            modelBuilder.Entity("UAMPass.Models.Pasantia", b =>
            {
                b.HasOne("UAMPass.Models.Empresa", "Empresa") // Pasantia.Empresa navigation
                    .WithMany("Pasantias") // Empresa tiene colección Pasantias
                    .HasForeignKey("EmpresaId") // FK en Pasantias
                    .OnDelete(DeleteBehavior.Cascade) // borrar empresa borra pasantias relacionadas
                    .IsRequired();

                b.Navigation("Empresa");
            });

            // Propiedades de navegación informadas explícitamente (uso interno de EF)
            modelBuilder.Entity("UAMPass.Models.Empresa", b =>
            {
                b.Navigation("Pasantias");
            });

            modelBuilder.Entity("UAMPass.Models.Estudiante", b =>
            {
                b.Navigation("Aplicaciones");
            });

            modelBuilder.Entity("UAMPass.Models.Pasantia", b =>
            {
                b.Navigation("Aplicaciones");
            });

#pragma warning restore 612, 618 // restaurar warnings
        }
    }
}